base_url = "https://sinono3.github.io"
theme = "papaya"
default_language = "en"

[markdown]
highlight_code = true

[languages]

[languages.en]
title = "Aldo Acevedo"
description = """
Guy who did software engineering, graphics programming, game development.
__Incursioning in machine learning and mechanistic interpretability.__
[Learn more about me.](/about)

[**Esta página está disponible en Español.**](/es)
"""

build_search_index = true
generate_feeds = true
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]

[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
recent_projects = "Recent Projects"
more_projects = "More Projects"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
# Customize your post date format. See: https://tera.netlify.app/docs/#date
date_format = "%B %e, %Y"

games = "Games"
music = "Music"
ES = "ES"
EN = "EN"

[languages.es]
title = "Aldo Acevedo"
description = """
Personaje que desarrolló software, gráficos y videojuegos.
__Ahora estoy incursionando en machine learning e interpretabilidad mecanística.__
[Conoce más acerca de mí.](/about)

[**This page is available in English.**](/)
"""
build_search_index = true
generate_feeds = true
taxonomies = [
    { name = "tags", feed = true, lang = "es" },
    { name = "categories", feed = true, lang = "es" },
]

[languages.es.translations]
projects = "Proyectos"
blog = "Blog"
about = "Acerca de"
recent_projects = "Proyectos recientes"
more_projects = "Más proyectos"
recent_blog_posts = "Posts recientes"
more_blog_posts = "Más posts"
tag = "Etiqueta"
tags = "Etiquetas"
to_all_tags = "Todas las etiquetas"
category = "Categoría"
categories = "Categorías"
to_all_categories = "Todas las categorías"
view_by = "Ver por"
other = "Otros"
minute = "min"
prev_page = "Posts más nuevos"
next_page = "Posts más viejos"
# Customize your post date format. See: https://tera.netlify.app/docs/#date
date_format = "%B %e, %Y"

games = "Jueguitos"
music = "Música"
ES = "ES"
EN = "EN"

[extra]
env = "ZOLA_ENV"
color_mode = "light"

# List of Papaya navigational menu items. Used to construct the navigation bar. See the README for item schema.
menu_items = [
    { name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 5, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    { name = "projects", url = "$LANG_BASE_URL/projects", show_recent = true, recent_items = 2, recent_trans_key = "recent_projects", more_trans_key = "more_projects" },
    { name = "games", url = "$LANG_BASE_URL/games"},
    { name = "music", url = "$LANG_BASE_URL/music"},
    { name = "about", url = "$LANG_BASE_URL/about", show_recent = false },
]

[extra.images]
# Width defined in pixels
max_width = 2500


# Open Graph Protocol objects. See: https://ogp.me/
[extra.ogp]
locale = "en_US"
first_name = "Aldo"
last_name = "Acevedo"
gender = "male"
username = "sinono3"

[extra.social]
email = "aldoacevedo@protonmail.com"
github = "Sinono3"
linkedin = "aldo-acevedo-9a38a9289"

[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
